### ISSUE TITLE
Kernel is only built using one core?

### ISSUE THREAD

**Issue by un65esoq** [NUS-Curiosity/KernJC#5]
Hey, thanks for making the artifacts available!

I believe the $(nproc) in https://github.com/NUS-Curiosity/KernJC/blob/9a331e5237fa0e8c22e90a6df59ede40d3d4267a/src/env_manager.py#L527 is not actually evaluated (because it's a Python string), thus the kernel is built with one CPU only. Can anyone confirm this?

**Comment by brant-ruan** [comment]
Hi, thank you for pointing out this issue. It is now fixed by obtaining and delivering the exact number to the shell.

**Comment by luisgerhorst** [comment]
Thank you!
